development:
  adapter: postgresql
  database: dry_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: dry_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dry_production
  pool: 5
  timeout: 5000